//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLModel.Models.BarrierFreeTMSModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutTrip
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string tempname { get; set; }
        public string tripId { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<int> AuthorizeType { get; set; }
        public string H0001 { get; set; }
        public string H0102 { get; set; }
        public string H0203 { get; set; }
        public string H0304 { get; set; }
        public string H0405 { get; set; }
        public string H0506 { get; set; }
        public string H0607 { get; set; }
        public string H0708 { get; set; }
        public string H0809 { get; set; }
        public string H0910 { get; set; }
        public string H1011 { get; set; }
        public string H1112 { get; set; }
        public string H1213 { get; set; }
        public string H1314 { get; set; }
        public string H1415 { get; set; }
        public string H1516 { get; set; }
        public string H1617 { get; set; }
        public string H1718 { get; set; }
        public string H1819 { get; set; }
        public string H1920 { get; set; }
        public string H2021 { get; set; }
        public string H2122 { get; set; }
        public string H2223 { get; set; }
        public string H2300 { get; set; }
        public string username { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<bool> isClose { get; set; }
    }
}
