//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLModel.Models.BarrierFreeTMSModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiDriver
    {
        public int TaxiDriverId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> TaxiId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<decimal> LoginMilage { get; set; }
        public Nullable<decimal> ReturnMilage { get; set; }
    
        public virtual Taxi Taxi { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
