//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLModel.Models.BarrierFreeTMSModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxi()
        {
            this.TaxiDriver = new HashSet<TaxiDriver>();
        }
    
        public int TaxiId { get; set; }
        public string LicensePlateNumber { get; set; }
        public Nullable<int> CarModelId { get; set; }
        public string CarBodyNo { get; set; }
        public string TaxiCallNo { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<int> TaxiCompanyId { get; set; }
        public string CarHeaderPhoto { get; set; }
        public string LeftSidePhoto { get; set; }
        public string RightSidePhoto { get; set; }
        public string RearPhoto { get; set; }
        public string InsideFrontPhoto { get; set; }
        public string InsideBackPhoto { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string Remark { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> LastTaxiStopId { get; set; }
        public Nullable<System.DateTime> LastEntryDTime { get; set; }
        public string ParkingLot { get; set; }
        public Nullable<decimal> TotalMilage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxiDriver> TaxiDriver { get; set; }
    }
}
