//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLModel.Models.BarrierFreePassengerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string PassengerId { get; set; }
        public string TaxId { get; set; }
        public string Start_Address { get; set; }
        public Nullable<double> Start_Latitude { get; set; }
        public Nullable<double> Start_Longitude { get; set; }
        public string Target_Address { get; set; }
        public Nullable<double> Target_Latitude { get; set; }
        public Nullable<double> Target_Longitude { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<int> EstimatedFare { get; set; }
        public Nullable<int> EstimatedTime { get; set; }
        public Nullable<byte> ProcessStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<int> CancelBy { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public Nullable<System.Guid> OrderNo { get; set; }
        public Nullable<int> TaxiId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string AdditionMessage { get; set; }
        public string BuyerIdentifier { get; set; }
        public Nullable<int> TaxiCompanyGroupId { get; set; }
        public string CreateAccount { get; set; }
    }
}
