//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLModel.Models.BarrierFreePassengerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtendBarriers
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string IdentityNumber { get; set; }
        public string Sex { get; set; }
        public int Economic { get; set; }
        public bool FullPayment { get; set; }
        public bool Aborigines { get; set; }
        public bool Student { get; set; }
        public string PostalCode1 { get; set; }
        public string PostalCode2 { get; set; }
        public int BarriersManual { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public int BarriersLevel { get; set; }
        public int BarriersCategory { get; set; }
        public string BarriersCode { get; set; }
        public int Diagnostic { get; set; }
        public int ReservationDays { get; set; }
        public Nullable<System.DateTime> SuspensionBegin { get; set; }
        public Nullable<System.DateTime> SuspensionEnd { get; set; }
        public bool CarPool { get; set; }
        public bool Wheelchair { get; set; }
        public int WheelchairCategory { get; set; }
        public bool VisualDisturbance { get; set; }
        public Nullable<bool> isLongCare { get; set; }
        public int LongTermDisability { get; set; }
        public string RelationshipName { get; set; }
        public string Relation { get; set; }
        public string EmergencyPhone { get; set; }
        public string DisabilityPhoto { get; set; }
        public string EconomicStatusPhoto { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> isDisabled { get; set; }
        public Nullable<System.DateTime> DisabledTime { get; set; }
        public Nullable<System.DateTime> insDateTime { get; set; }
        public Nullable<System.DateTime> updDateTime { get; set; }
        public decimal SubsidyLimitAmtMon { get; set; }
        public int SubsidyTripMon { get; set; }
        public bool OnlineBooking { get; set; }
    }
}
